package me.einjojo.playfair;

import me.einjojo.playfair.util.Playfair;
import java.util.Scanner;

/**
 * @author - Ein_Jojo
 *
 * Created at 10.09.21 22:21
 */
public class Main {

    Playfair playfair;
    private final Scanner scanner = new Scanner(System.in);

    public static void main(String[] args) {
        Main main = new Main();
        main.run();
    }

    private void initPlayfair() {
        System.out.print("Please enter a key: ");

        String key = scanner.next();
        this.playfair = new Playfair(key);
    }

    private void clearConsole() {
        for (int i = 0; i < 50; i++) {
            System.out.println();
        }
    }

    public void run() {
        System.out.println("▀███▀▀▀██▄▀████▀         ██     ▀███▀   ▀██▀███▀▀▀███     ██     ▀████▀███▀▀▀██▄");
        System.out.println("  ██   ▀██▄ ██          ▄██▄      ███   ▄█   ██    ▀█    ▄██▄      ██   ██   ▀██▄   ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄");
        System.out.println("  ██   ▄██  ██         ▄█▀██▄      ███ ▄█    ██   █     ▄█▀██▄     ██   ██   ▄██    █▀▄▀██▄██▀▄▄▀█ ████ ▄▄█ ▄▄▀");
        System.out.println("  ███████   ██        ▄█  ▀██       ████     ██▀▀██    ▄█  ▀██     ██   ███████     █ █▀██ ▄█ ▀▀ █ ▄▄ █ ▄▄█ ▀▀▄");
        System.out.println("  ██        ██     ▄  ████████       ██      ██   █    ████████    ██   ██  ██▄     ██▄██▄▄▄█ ████▄██▄█▄▄▄█▄█▄▄");
        System.out.println("  ██        ██    ▄█ █▀      ██      ██      ██       █▀      ██   ██   ██   ▀██▄   ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀");
        System.out.println("▄████▄    ████████████▄   ▄████▄  ▄████▄  ▄████▄   ▄███▄   ▄████▄████▄████▄ ▄███▄");
        //Text generated by https://texteditor.com"
        System.out.println("\nJava implementation Developed by Ein_Jojo / Johannes");
        initPlayfair();
        clearConsole();
        showSelector();
    }
    private void showSelections() {
        System.out.println("[USAGE]");
        System.out.println("1. Encrypt a text");
    //    System.out.println("2. Decrypt a cipher");
        System.out.println("3. Change Key");
        System.out.println("4. Clear the console");
        System.out.println("5. Print Matrix");
        System.out.println("0. Exit");
    }

    private void showSelector() {
        showSelections();
        while(true) {
            System.out.println("Enter a number: ");
            String input = scanner.next();

            switch (input) {
                case "0":
                    System.out.println("Good bye!...");
                    return;
                case "1":
                    encryptForm();
                    break;
                case "2":
                    //TODO: Implement decrypter
                    break;
                case "3":
                    changeKeyForm();
                    break;
                case "4":
                    clearConsole();
                    showSelections();
                    break;
                case "5":
                    printMatrix();
                    break;
                default:
                    System.out.printf("Unknown command: %s\n", input);
            }
        }
    }




    private void printMatrix() {
        playfair.printMatrix();
    }

    private void changeKeyForm() {
        System.out.print("Enter new key: ");
        String key = scanner.next();
        playfair.setKey(key);
        System.out.println("The key was successfully changed!");
    }

    private void encryptForm() {
        Scanner tScanner = new Scanner(System.in);
        System.out.println("Enter the text you want to encrypt: ");
        String text = tScanner.nextLine();
        String e = playfair.encrypt(text);
        System.out.println(e);
        System.out.println();

    }
}
